### ISSUE TITLE
Consider to remove hard-coded duo lib from your repo

### ISSUE THREAD

**Issue by matej-prokop** [LINKIWI/react-duo-web#3]
Hi, 

Currently, duo lib is hard-coded (copy-pasted) within your repo to avoid using <script> tag.  However, there is official npm package for it https://www.npmjs.com/package/duo_web from Duo

Consider to use it ;) Then you would simply replace `import duoWeb from '../lib/duo-web';` within duo.js by `import duoWeb from 'duo_web'` and you can removed their script from your repo.

**Comment by LINKIWI** [comment]
Hello, using `duo_web` as a versioned dependency was the original intention but the `duo_web` package has not been published to npm in 3 years despite many merged code changes. I think I did this originally but the version that was published was so old that it was missing some patches that caused some problems in this wrapper library. I can't exactly remember what the issue was, but I can try revisiting this to see what can be done.

**Comment by LINKIWI** [comment]
I vaguely remember some name-clashing issues related to the fact that the `duo_web` library adds a global `Duo` to the `window` object. I believe I specifically modified the code that is currently in `lib` so that it properly returns an instance of the object rather than arbitrarily modifying globals.

**Comment by matej-prokop** [comment]
Thank you for replying so quickly. Sadly, you are right. I didn't notice that they are not publishing new changes to npm. (I was looking into their github repo which is updated from time to time)
